### PR TITLE
Only generate code for 'break' and 'continue' edge cases if they are …

### PR DESCRIPTION
**Pull request by harpocrates**
…used.

Yeah, the output isn't yet as simple as it could be. I'll follow this up with more simplifications and more testing, but wanted to let you put down your comments - I may be away from my computer for a bit.

### CODE REVIEW

**Comment by harpocrates** [comment]
Yeah, so the changes I just made are (conveniently) orthogonal to your suggestions - just simplified AST produced a bit. Now, `strcmp.c` gives something a lot more pleasant. 😃 

``` haskell
#[no_mangle]
pub unsafe fn strcmp(mut l : *const u8, mut r : *const u8) -> i32 {
    {   while *l == *r && (*l != 0) {
            {
                l = l.offset(1 as (isize));
                r = r.offset(1 as (isize));
            }
        }
    }
    (*(l as (*mut u8))).wrapping_sub(*(r as (*mut u8))) as (i32)
}
```

I definitely see what you mean for restructuring with `usesBreak` and `usesContinue`. And nice find for `Data.Monoid.Any`. All this will be much nicer. I look forward to implementing it (if you don't end up beating me to it). I'll try to do this sometime this weekend.

**Comment by harpocrates** [comment]
Alright. I implemented your suggestions.

**Comment by jameysharp** [comment]
Very nice work--this is substantially better than what I was generating before!

It occurs to me that the AST simplifications commit is not strictly correct though. Consider this C function, which is bad and nobody should do this but it is legal C:

``` c
extern int printf(const char *fmt, ...);
void f(void)
{
  for(int i = 0; i < 3; ++i)
  {
    printf("%d\n", i);
    int i = 20;
    printf("%d\n", i);
  }
}
```

If we bring the loop body out to the same block as the increment statements, then the inner `i` will be in scope during the increment, rather than the outer `i`. So I think you'd best not use `toBlock` in the no-loop case. It's ugly, but let's wait to talk about what we could safely do instead until after merging the work you've done so far.

On the other hand, you _can_ safely use `toBlock` on `incr'` because that is never followed by any other statements... which I now realize I could have done at any time...

Also, the third commit doesn't compile unless you remove the two remaining lines that mention `loopingEscapes`. But I've tested it with that fixed and I'm fully happy with it!

Could you fix those issues?

(I think GitHub deleted my earlier comments because I attached them to a commit which you later rebased, rather than to this pull request, so I guess I should learn not to do that again...)

**Comment by jameysharp** [comment]
Oh, a couple tiny little nitpicks around the sentence containing "code to deal with edge cases - see the case of `interpretStatemen`":
- I prefer "`&mdash;`" over " - " because I'm a typography nerd, I guess?
- "interpretStatement" is missing its final "t".

Other than those little things, I think the documentation you wrote for this is great and I really appreciate you doing it!

**Comment by harpocrates** [comment]
Very nice catch with illegal AST simplification example! Here's what it looks like now:

``` rust
extern {
    fn printf(fmt : *const u8, ...) -> i32;
}
#[no_mangle]
pub unsafe fn f() {
    ({
         let mut i : i32 = 0i32;
         while i < 3i32 {
             {
                 printf(b"%d\n\0".as_ptr(),i);
                 let mut i : i32 = 20i32;
                 printf(b"%d\n\0".as_ptr(),i);
             }
             i = i + 1;
         }
     })
}
```

Even `strcmp.c` looks better (IMO). There is obviously still some work to do in simplification for cases when the increment could really be inside the same scope as the loop body - although now that I think about it, that just seems like a specific instance of a more general simplification you could sometimes get by flattening nested scope.

Some small simplifications like merging nested scopes (that can be safely merged) could be filtered out using smart constructors, but that will be for another pull request. Maybe even for "idiomatic" if things turn out to be hairier than I anticipate... 😃

**Comment by jameysharp** [comment]
This is so great and I've merged it. Thank you!

Here's a thought about the extra braces.

One of my design goals for Corrode is that if the C source has some construct in it and we can preserve it, then the Rust output should have that construct too. The flip side of that is that if we can avoid introducing constructs that weren't in the C source, as in commit  4e50186 that I pushed last night, then we should.

Following that principle, if the source has a `CCompound` statement in it, then the output should have a block; but if we can avoid adding any other blocks, we should.

I'm wondering if the easiest way to handle that is to change `interpretStatement`'s return type from `Rust.Expr` to `[Rust.Stmt]`. Then:
- the empty statement case can return an empty list;
- `CFor` can return a list of assignments followed by the loop when `initial` is `Left _`, or generate a block like it does now if it needs let-bindings;
- and every other case can return the same thing it does now, but wrapped in `[Rust.Stmt ...]`.

I'd also be fine with a special case on `CCompound`, where if `stmts` turns out to be an empty list then we return an empty list instead of a new block.

At a quick glance, it looks like this will get rid of nearly all calls of `toBlock`, too, which strikes me as a nice simplification.

Want to give that a shot and see how it goes?

**Pull request merged**
