### PR TITLE
Adding partial initialization of structs

### PR DESCRIPTION
**Pull request by harpocrates**
To the best of my understanding of C99, this implements partial initialization ([previous discussion](https://github.com/jameysharp/corrode/pull/37)), dealing with zeroing and out of order fields.

``` c
struct grade {
  float percentage;
  int failing;
};
struct student {
  struct student *friends;
  int age;
  struct grade marks;
};

void f() {
  struct student s;
  s = (struct student) { };
  s = (struct student) { .age = 9 };
  s = (struct student) { .age = 9, { 0.45, 1 } };
  s = (struct student) { .age = 9, { .percentage = 0.45, .failing = 1 } };
  s = (struct student) { 0, 9, { 0.45, 1 } };
  s = (struct student) { .marks = { 0.45, 1 }, .age = 9 };
}
```

compiles to

``` rust
#[derive(Clone, Copy)]
#[repr(C)]
pub struct grade {
    pub percentage : f32,
    pub failing : i32,
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct student {
    pub friends : *mut student,
    pub age : i32,
    pub marks : grade,
}

#[no_mangle]
pub unsafe fn f() {
    let mut s : student;
    s = student {
            friends: 0 as (*mut student),
            age: 0i32,
            marks: grade { percentage: 0f32, failing: 0i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0f32, failing: 0i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0i32 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
}
```

And code that has too many initializers or designators that do not correspond to fields or non-member designators is dealt with via `badSource`.

One thing that isn't clear to me from the C99 spec on initialization (6.7.8) - when does it make sense to have multiple designators for a given initializer? Seems like point 18 addresses this, and I think this means I am rejecting valid code, since I currently assume that an initializer can have at most one designator (and it must be a member designator)...

### CODE REVIEW

**Comment by harpocrates** [comment]
Never mind. I found the clarification I needed [here](http://en.cppreference.com/w/c/language/struct_initialization). Fixing now this (I think) last case.

**Comment by jameysharp** [comment]
`orderInits` is making my head hurt. :wink: For a start: I didn't realize `null` works over `Foldable` these days, so using it on a `Maybe` was super confusing for a bit! I'd like to be able to point at most constructs in Corrode and identify a Rust equivalent (I've been feeling a little bad about using `<$>` even) so I'm thinking avoiding FTP magic might be better.

I think we can rewrite this to more explicitly say what it's doing&mdash;and also to avoid partial functions like `fromJust`, which make me nervous even though I can sketch a proof that this one is OK.

Also, a tricky thing in C99 6.7.8 is that the same field can be initialized multiple times, and only the last one is used. (See example 12.) It's implementation-defined whether the unused initializer expressions have their side effects evaluated, so we can choose to just throw them away. It's not clear to me whether this implementation handles that case correctly, but I think we can make it fall out naturally...

Let's talk about initializer representation first. I think the result we want looks like this, after all designators are resolved:

``` haskell
import qualified Data.IntMap.Strict as IntMap

data Initializer
    = Scalar Rust.Expr (IntMap.IntMap Initializer)
    | Aggregate (IntMap.IntMap Initializer)
```

For a struct, the keys in an IntMap correspond to fields in declaration order. Eventually we'll support arrays and the keys will have the obvious meaning there. The map in `Scalar` is similar but represents functional updates to an expression of structure type.

For example, you'd get this `Initializer` from either `.marks.failing = 42`, or from `42` when the previous element was designated with `.marks.percentage`:

``` haskell
Aggregate $ IntMap.singleton 2 $ Aggregate $ IntMap.singleton 1 $ Scalar 42 IntMap.empty
```

(I'm noticing that I used `badSource` somewhere I shouldn't have. Scalar initializers are allowed for struct-typed declarations, as long as the scalar has the appropriate struct type. See C99 6.7.8 paragraph 13.)

I picture initialization proceeding as a two-step pipeline:

First, for each element of a `CInitList`, resolve its "current object" per C99 6.7.8 paragraphs 17-18 and footnotes 129-131. A "current object" is a list of field indexes and types of the remaining fields, including this one. If current object is an empty list, then we've initialized every field and can't initialize any more.

``` haskell
type CurrentObject = [(Int, CType, [CType])]
```

Given your example types, `.marks.failing` looks like:

``` haskell
[(2, IsStruct "grade" ..., []]), (1, IsInt Signed (BitWidth 32), [])]
```

We can compute a `CurrentObject` from a list of designators:

``` haskell
objectFromDesignators :: CType -> [CDesignator] -> EnvMonad CurrentObject
objectFromDesignators _ [] = return []
objectFromDesignators (IsStruct name fields) (d@(CMemberDesig ident _) : ds) =
    case span (\ (field, _) -> identToString ident /= field) fields of
        (earlier, (_, ty) : rest) -> do
            sub <- objectFromDesignators ty ds
            return ((length earlier, ty, map snd rest) : sub)
        (_, []) -> badSource d ("designator for field not in struct " ++ name)
objectFromDesignators ty (d : _) = badSource d ("designator for " ++ show ty)
```

And we can compute the next `CurrentObject`, if we haven't reached the end of the struct.

``` haskell
nextObject :: CurrentObject -> CurrentObject
nextObject [] = []
nextObject (cur : sub) = case nextObject sub of
    [] -> case cur of
        (_, _, []) -> []
        (idx, _, next : fields) -> [(idx + 1, next, fields)]
    rest -> cur : rest
```

Resolution takes a current object to use if no designator is specified. It returns the new current object for the next element to use, and the above `Initializer` type representing the part of the object that this element initialized.

``` haskell
resolveCurrentObject
    :: CurrentObject
    -> (CurrentObject, CInit)
    -> (CurrentObject, EnvMonad Initializer)
```

Note that `resolveCurrentObject` has the right type to use with [`mapAccumL`](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-List.html#v:mapAccumL), and the result list can be passed to `sequence` to collect any errors.

Yet another tricky thing: consider C99 6.7.8 examples 5 and 11, and see paragraph 20. I read that as saying that if our current or designated object has an `IsStruct` type and we see a `CInitExpr`, then we need to recurse with the current object being the first field of the struct instead. It's not clear to me how that interacts with paragraph 13, if the init expr has a struct type...

Second, once we have a list of `Initializer`s, we need to merge them together. Scalar values entirely replace any earlier initialization for the same designator list. Aggregate values can replace parts of earlier aggregates, or parts of earlier scalars! The latter case should translate to Rust's [functional update syntax](https://doc.rust-lang.org/reference.html#struct-expressions). This addresses C99 6.7.8 paragraph 23, part of paragraph 19, and footnotes 132 and 133.

``` haskell
mergeInitializer :: Initializer -> Initializer -> Initializer
mergeInitializer _ b@(Scalar{}) = b
mergeInitializer (Aggregate a) (Aggregate b) = Aggregate (IntMap.unionWith mergeInitializer a b)
mergeInitializer (Scalar s a) (Aggregate b) = Scalar s (IntMap.unionWith mergeInitializer a b)
```

Then `foldr mergeInitializer (Aggregate IntMap.empty)` should produce the final `Initializer` which we can translate to a `Rust.Expr`.

Phew. Um... I hope that was helpful?

**Comment by harpocrates** [comment]
Yes, that's very helpful and definitely helps add to my current stew of thoughts! I agree with the functional update, although I would like to clarify another edge case. Given something like

``` c
struct U {
  int u1
  int u2;
};
struct T {
  struct U t1;
  int t2;
};
struct S {
  struct T s1;
};

struct S s = { .s1 = <some expression>, .s1.t1.u1 = 1 };
```

it is tempting to naively translate to

```
let mut s : S = S { s1: T { t1: U { u1: 1, ..<some expression>.t1 }, ..<some expression>  } };
```

which, given `<some expression>` can have side effects, means we should really be translating to

```
let mut s : S = {
  let mut t : T = <some expression>;
  S { s1: T { t1: U { u1: 1, ..t.t1 }, ..t } }
};
```

right?

**Comment by jameysharp** [comment]
Oh, huh. Um... Yeah, I think that is what you have to do, because I assume functional update syntax doesn't let you update nested fields. Good catch!

That said, I guess it depends on how you interpret the interaction between C99 6.7.8 paragraphs 13 and 20. (Oh god I'm memorizing paragraph numbers in C99 now, send help) Is it even legal to initialize `.s1` from an expression? I could interpret paragraph 13 as only allowing initialization from a structure expression when it's not inside braces.

Here's a slightly simpler version of your example, and it produces different results on gcc than on clang 3.7 or later. So yay, I guess we're exploring either buggy territory or undefined behavior?

[Compiler Explorer link](https://godbolt.org/g/gPL0iK)

**Comment by harpocrates** [comment]
Haha, alright. 😄 

I'll start by getting the defined behavior right... I'm not sure I will end up getting around to this today, but I have my fingers crossed.

**Comment by jameysharp** [comment]
Answer from the always-informative [@spun_off](https://twitter.com/spun_off) on Twitter:

https://twitter.com/spun_off/status/753726635887788032

> recent Clang iz right, GCC is wrong. TrustInSoft/tis-interpreter#81

https://twitter.com/spun_off/status/753727338798612480

> standard remains ambiguous even after [clarification](http://open-std.org/jtc1/sc22/wg14/www/docs/dr_413.htm).

The [C standard defect report](http://open-std.org/jtc1/sc22/wg14/www/docs/dr_413.htm) includes an example of initializing a designated subaggregate from a struct-typed expression, so the standards committee apparently believes that's OK, and also that the updates from the later designated initializers don't change unrelated values copied from the earlier expression.

**Comment by harpocrates** [comment]
Alright, I've finally gotten around to thinking more about this. Your ideas are great and I think I've implemented pretty much all of them, but there is one final sticking point which I haven't figured out (which actually causes almost everything to be buggy). Consider

``` c
struct s {
   int a;
   int b;
}
struct t {
  struct s c;
}
...
struct t x = { y }
```

Then is `y` the first `int` field of `c`, or the whole of `c` in the example below? Depends on whether `y` is an `int` or `struct s`!

Essentially, the current object is not always well-defined - it can at times take on a range of values. Any ideas on how to treat this in the general case? Seems like we may even need to also extract type information from the initializers...

The current implementation I committed is faulty (for the above reasons), but I usually find it easier to think with something mostly ok in front of my eyes than nothing. 😄

**Comment by harpocrates** [comment]
I think I may have a way to solve these problems. I'll try to find time to type up my thoughts later.

**Comment by harpocrates** [comment]
Alright, I think this is finally approaching completion. As far as I can tell it translates all valid C programs to valid Rust. I'm not sure that it doesn't let through some invalid C programs (converting them to possibly wrong Rust). One notable exception to that uncertainty: I haven't disallowed empty initializers  (although they are technically illegal in C99) since both `gcc` and `clang` allow them.

Here are some examples of initializers this now accepts:

``` c
struct grade {
  float percentage;
  int failing;
};
struct student {
  struct grade marks;
  struct student *friends;
  int age;
};

void f() {
  struct grade g;
  struct student s;
  s = (struct student) { 4.56 }; 
  s = (struct student) { g }; 
  s = (struct student) { };
  s = (struct student) { .age = 9 };
  s = (struct student) { .marks.percentage = 0.45 };
  s = (struct student) { .marks.percentage = 0.45, .age = 9, .marks.failing = 1 };
  s = (struct student) { { .percentage = 0.45, .failing = 1 }, .age = 9 };
  s = (struct student) { .marks.failing = 1, 0, 9 };
}
```

translates to

``` rust
#[derive(Clone, Copy)]
#[repr(C)]
pub struct grade {
    pub percentage : f32,
    pub failing : i32,
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct student {
    pub friends : *mut student,
    pub age : i32,
    pub marks : grade,
}

#[no_mangle]
pub unsafe fn f() {
    let mut i : i32 = 2i32;
    let mut g
        : grade
        = grade { percentage: 0.45f64 as (f32), failing: 1i32 };
    let mut s : student;
    s = student { friends: 0 as (*mut student), age: 0i32, marks: g };
    s = student {
            friends: 0 as (*mut student),
            age: 0i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0f32, failing: 0i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0i32 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
    s = student {
            friends: 0i32 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 0i32 }
        };
    s = student {
            friends: 0 as (*mut student),
            age: 9i32,
            marks: grade { percentage: 0.45f64 as (f32), failing: 1i32 }
        };
}
```

When you get the chance, let me know what you think.

**Comment by jameysharp** [comment]
Overall this looks excellent and I'll be delighted to merge it. I have some
questions I want to throw out first though.

Why is comparing on `typeWidth` the right thing to do? I'd have expected to
check that either both are structure types or neither are, and if they're
structures then they both have the same name. If I'm missing something
about C, which is entirely possible, then I think that function needs more
documentation.

Does a `CInitList` ever need the `possibleCasts` magic or is that just for
`CInitExpr`?

Can `translateInitializer`, in the `CInitExpr` case, pick the unique legal
"possible cast" and commit to it? If not, what's an example of a C-legal
initializer which requires searching the space of possible casts across
multiple elements of an initializer list?

What if `zeroInitialize` returns an `Initializer` instead of an `Expr`?
Then you can fill in fields not otherwise mentioned all at once with

``` haskell
zeroInitialize ty `mappend` initial'
```

And if `interpretInitializer'` doesn't need to fill in zeroes, it can use
`forM` over `IntMap.toList` instead of the list monad thing that's
confusing me when I try to read it. :simple_smile:

What do you think?

**Comment by harpocrates** [comment]
About `typewidth`: I added this because for non-struct types, it doesn't matter if the types match, they just get cast to the required type. I've done some tests though, and for structs it should also check the struct name too... Should be a quick fix. Here's an example of something that is currently incorrectly translated because of this:

``` c
struct t {
    int i;
};
struct s {
    struct t x;
};

struct s y = { 3 };
```

> Does a `CInitList` ever need the `possibleCasts` magic or is that just for
> `CInitExpr`?

I think you meant that the other way around 😄, and no only, `CInitList` needs `possibleCasts` (and same for `nextObject`). Should I move them into the `where` of the `CInitList` case? I initially thought the literate explanation might flow more easily if they came before, but now I find myself leaning the other way...

> Can `translateInitializer`, in the `CInitExpr` case, pick the unique legal "possible cast" and commit to it? If not, what's an example of a C-legal initializer which requires searching the space of possible casts across multiple elements of an initializer list?

It might be possible, but I don't think so. I'm trying to remember the particulars, but this issue was the key thing that held everything up for so long. The main problem is that to pick the correct cast, you need to know what the initializer evaluates to, which requires you to actually interpret it. I think that nested initializer lists are the ones that require searching through the space of possible casts (because you don't get any hints about their types)...

> What if `zeroInitialize` returns an `Initializer` instead of an `Expr`?

Yep. I like that. But that means I will be moving `interpretInitializer'` to the (currently not existent) `where` block of `interpretInitializer`, since it now would have the precondition that all aggregates have every possible field filled.

**Comment by harpocrates** [comment]
Alright. `typeWidth` has been changed to `compatible` and correctly corrodes the example I gave in the previous comment to

``` rust
#[derive(Clone, Copy)]
#[repr(C)]
pub struct t {
    pub i : i32,
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct s {
    pub x : t,
}

#[no_mangle]
static mut y : s = s { x: t { i: 3i32 } };
```

I changed `zeroInitialize` to return an Initializer instead of an Expr, but I'm not sure these changes were worth it... I didn't go all the way with changing `interpretInitializer'`  (now just `helper` and inside the where clause of `interpretInitializer`) since things didn't get simpler after the change. If I pattern match against the type of initializer, yes I can use `forM` over `IntMap.toList` for the aggregate case, but I still end up having the lookup logic for the scalar case. Here's what it looked like:

``` haskell
helper :: CType -> Initializer -> Maybe Rust.Expr
helper _ (Scalar expr initials) | IntMap.null initials = Just expr

helper (IsStruct str fields) (Scalar expr initials) = Rust.StructExpr str <$> fields' <*> pure expr
    where

    fields' = sequence $ do
        ((field,ty),i) <- zip fields [0..]
        case IntMap.lookup i initials of
            Just initial -> case helper ty initial of
                Nothing -> pure Nothing
                Just initial' -> pure (Just (field, initial'))
            Nothing -> mzero

helper (IsStruct str fields) (Aggregate initials) = Rust.StructExpr str <$> fields' <*> pure Nothing
    where

    fields' = forM (fields `zip` IntMap.toList initials) $ \((field,ty),(_,initial) ->
        (,) field <$> helper ty initial

helper _ _ = Nothing
```

I actually think it might be better to return to having `zeroInitialize` returning an Expr. Thoughts?

**Comment by jameysharp** [comment]
`compatible` looks good!

Here's what I had in mind (though I haven't tested this, or even tried compiling it):

``` haskell
(expr,initials) = case initializer of
    Scalar e i -> (Just e, i)
    Aggregate i -> (Nothing, i)

fields' = forM (IntMap.toList initials) $ \ (idx, value) -> do
    (field, ty) <- listToMaybe (drop idx fields)
    value' <- interpretInitializer' ty value
    Just (field, value')
```

That should work for both scalar and aggregate. You just have to get all the zero-initializers filled in as part of the top-level `interpretInitializer` using

``` haskell
zeroInitialize ty `mappend` initial'
```

which will establish that invariant recursively all the way down the tree of nested structs.

For what it's worth, I have no problem keeping `interpretInitializer'` at the top of this section for documentation purposes even if it is capable of generating Rust expressions that won't compile. I think your instincts were good about what order to present this code in.

**Comment by jameysharp** [comment]
> I think that nested initializer lists are the ones that require searching through the space of possible casts (because you don't get any hints about their types)...

I'm pretty sure that when you see an initializer list in braces, you're not supposed to search down for a field where that list makes sense; it's supposed to immediately apply to, and complete, the current object. From C99 6.7.8 paragraph 20:

> If the initializer of a subaggregate or contained union begins with a left brace, the initializers enclosed by that brace and its matching right brace initialize the elements or members of the subaggregate or the contained union.

The next sentence covers the "find the right sub-object" magic, but only applies when there _isn't_ a left brace:

> Otherwise, only enough initializers from the list are taken to account for the elements or members of the subaggregate or the first member of the contained union; any remaining initializers are left to initialize the next element or member of the aggregate of which the current subaggregate or contained union is a part.

This is what I meant by asking if "a `CInitList` ever need the `possibleCasts` magic", and I said it the way around I meant :smile: but we were looking at it from opposite perspectives. Sure, you'd only use `possibleCasts` when you're in the middle of a `CInitList`, but I think you should only use it when the thing you encounter there is a `CInitExpr`.

And given that `compatible` just needs to check that either a) neither type is a struct or b) both are and they have the same name, I'll come back to my question about always picking the right cast.
- If you call `interpretExpr` on a `CInitExpr` and get back something that `IsStruct`, then you must be initializing a struct (or it's `badSource`) but if it isn't the _correct_ struct, then you need to dig down through the first field of each struct until you find one that _is_ correct (or it's also `badSource`). Right? Then, could more than one struct in that search be "correct"? I don't think so: a struct can't contain itself or else it would have infinite size, and different structs can't both satisfy the `compatible` check.
- On the other hand, if you get back something that's not `IsStruct`, then you need to dig down through every layer of structs until you find the scalar field at the leaves of the tree, and there can only be one of those.

So in either case I think there's exactly one legal choice and you can find it with a pretty straightforward loop.

Also, I'm really skeptical that anybody else is implementing a combinatorial search in their C compilers just to parse initializer lists. :grin:

**Comment by harpocrates** [comment]
Quite right about the nested compound initializers. In retrospect, it seems obvious that the C standard would not define something that would be so expensive to translate... I'll get this done later today when I have time. Thanks a lot for pointing that out!!! 👍 

Meanwhile, I dropped in the fix you proposed for `interpretInitializers` - it is a lot nicer (and more readable!) than having to work with the list `MonadPlus` instance.

**Comment by jameysharp** [comment]
By the way: Once you're ready for this branch to be merged, I want to take care of merging it with the other work that's landed on master, so please leave that to me rather than rebasing or merging it yourself. I want to think carefully about how this interacts with the other changes that have gone in over the last week. I don't expect anything to be too tricky, but you never know... Thanks!

**Comment by harpocrates** [comment]
Sorry for the delay! My summer internship job has been ramping up a bit...

Alright - it took me a while to understand exactly what the C specification does. I believe I now have the desired behavior, but I wanted to double check the behavior with you before attempting to optimize (maybe optimize is the wrong word - I believe that this now has the desired linear complexity, but that isn't obvious at all from looking at it 😝).

Here is the edge case that was bugging me. Does the first element in the initializer list point to the first field of the type it is initializing or to the whole type? I think the answer is that it depends on whether that type is primitive or not. For example:

```
struct point { int x, y };

int i = { 1, 3 }; \\ the whole of i gets initialized to 1 (and 3 is ignored) since i is not a struct
struct point p = { 1, 3 }; \\ the fields of p get initialized to 1 and 3 since p is a struct
```

Thoughts on this? Is the code now accepting C99 initializers and only C99 initializers? 😉

**Comment by jameysharp** [comment]
Welcome back! It's not like I'm paying you, so I appreciate whatever time you choose to spend on Corrode. :smile:

Your interpretation of those examples makes sense to me, and also it seems to agree with GCC and Clang, judging by this [Compiler Explorer link](https://godbolt.org/g/UmFfGN). (The Intel C Compiler fails to compile it, with a mysterious error message, but whatever, I don't really care about them. :wink:)

I don't understand what problem you're solving with the "Fix edge case" commit (for future commits like that, it's helpful to include an example of the kind of code it would have miscompiled) but I'm willing to believe it. For the benefit of future readers, I think it'll be helpful if you can include some examples in the documentation of different cases and how your code handles them, like I tried to do for the section on "Declarations".

I'm eagerly looking forward to merging this, and I think it's almost ready. :smile:

**Comment by harpocrates** [comment]
Haha, the edge case I'm fixing is the one in the previous comment concerning initializing a primitive versus a struct (and the different behavior of the current object in those cases) - I couldn't think of a better name for the commit. 😄 But yeah, I will definitely add more documentation in the code too; these last two commits were very tentative as I wasn't sure if they even had the desired behaviour.

That said, I'm also going to get to work on seeing if / how I can make the code look cleaner and more self-documenting too.

**Comment by harpocrates** [comment]
Alright, unless you have any ideas, I think this is pretty much ripe for the merge. I would've liked to get rid of `mapAccumLM`, but I don't see a way of doing that without duplicating the code for the `CInitExpr` case of `translateInitializer` or changing the type of `translateInitializer` altogether. Both of those ended up being more confusing to read.

One final remark: we are currently accepting empty initializer lists. Although this is technically NOT C99 (but it is a GNU extension I think) I recommend we leave this in.

**Comment by jameysharp** [comment]
Reviewed, tested on musl libc, and merged! I made some edits for things I found confusing; if you find that I broke anything in the process, please let me know.

Thank you for putting all this work in! This made a big dent in the remaining issues that musl libc reveals, for example.

**Comment by harpocrates** [comment]
Wow! Things look a lot cleaner after your changes. Thanks a lot for putting in the much less exciting work of reviewing everything. 😃 

Side note - I now remember why initially I'd defined `zeroInitialize :: CType -> Rust.Expr` instead of `zeroInitializer :: CType -> EnvMonad Rust.Expr` - the former would have allowed us to address the fixme about non-scalar static variables.

> FIXME: Construct a correct default value for non-scalar static variables.

by changing

```
makeStaticBinding = (Rust.Item [] Rust.Private, makeBinding)
    ...
        (Rust.Static mut var ty (fromMaybe 0 mexpr))
   ...
```

to 

```
makeStaticBinding = (Rust.Item [] Rust.Private, makeBinding)
    ...
        (Rust.Static mut var ty (fromMaybe (zeroInitialize ty) mexpr))
   ...
```

Thoughts? I can throw this into a (small 😄) PR if you think it is worth it.

**Comment by jameysharp** [comment]
Oh, I see your point! But I really want to be able to report errors during zero-initialization since some of the cases are nonsense and enums are just hard.

I think the best answer is to call interpretInitializer from interpretDeclaration, with a synthesized CInitList if there's no actual initializer. Compare with how I did that in the case of variables declared static.

Then we need to pick some way to avoid emitting initializers for automatic-storage variables that didn't have one originally. Best I can come up with is to pass a boolean flag to makeBinding indicating whether the original init expression `isJust`. Making static bindings would ignore the flag, while making let bindings would use the flag to decide whether to produce Nothing or Just.

But I'm not super fond of that plan so if you have other suggestions, fire away!

**Comment by harpocrates** [comment]
Yeah - no better idea off the top of my head. I'll keep thinking about this for a couple days. I see your point about reporting errors - that does seem more important... 😕

**Pull request merged**
